//
//  StyleKit.m
//  GraphView
//
//  Created by Javier Loucim on 20/1/15.
//  Copyright (c) 2015 FuzeIdea. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawBubbleWithStrokeColor: (UIColor*)strokeColor fillColor: (UIColor*)fillColor fontColor: (UIColor*)fontColor label: (NSString*)label fontSize: (CGFloat)fontSize strokeWidth: (CGFloat)strokeWidth size: (CGSize)size;
{

    //// Variable Declarations
    CGSize textSize = CGSizeMake(size.width * 0.75, size.height * 0.75);
    CGPoint initialCoordinates = CGPointMake(5, 5);
    CGPoint textCoordinate = CGPointMake(size.width * 0.125 + initialCoordinates.x, size.height * 0.125 + initialCoordinates.y);

    //// Circle Drawing
    UIBezierPath* circlePath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(initialCoordinates.x, initialCoordinates.y, size.width, size.height)];
    [fillColor setFill];
    [circlePath fill];
    [strokeColor setStroke];
    circlePath.lineWidth = strokeWidth;
    [circlePath stroke];


    //// CircleText Drawing
    CGRect circleTextRect = CGRectMake(textCoordinate.x, textCoordinate.y, textSize.width, textSize.height);
    NSMutableParagraphStyle* circleTextStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
    circleTextStyle.alignment = NSTextAlignmentCenter;

    NSDictionary* circleTextFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Helvetica" size: fontSize], NSForegroundColorAttributeName: fontColor, NSParagraphStyleAttributeName: circleTextStyle};

    [label drawInRect: CGRectOffset(circleTextRect, 0, (CGRectGetHeight(circleTextRect) - [label boundingRectWithSize: circleTextRect.size options: NSStringDrawingUsesLineFragmentOrigin attributes: circleTextFontAttributes context: nil].size.height) / 2) withAttributes: circleTextFontAttributes];
}

@end
