//
//  StyleKit.h
//  GraphView
//
//  Created by Javier Loucim on 22/1/15.
//  Copyright (c) 2015 FuzeIdea. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawBubbleWithStrokeColor: (UIColor*)strokeColor fillColor: (UIColor*)fillColor fontColor: (UIColor*)fontColor label: (NSString*)label fontSize: (CGFloat)fontSize strokeWidth: (CGFloat)strokeWidth size: (CGSize)size percentage: (CGFloat)percentage;

@end
